theme: jekyll-theme-minimal
title: R Contributor Site
description: A site for people interested in contributing to R core -
  the code and documentation that gets distributed as base R.
logo: assets/img/Rlogo.png
description:
show_downloads: false
github:
  is_project_page: false
owner_url: working-group
owner_name: the R Contribution Working Group
image: assets/img/Rlogo-white.png
mastodon: https://hachyderm.io/@R_Contributors
mastodon_alt: R Contributors Mastodon profile
twitter: R_Contributors
twitter_alt: R Contributors Twitter profile
github: r-devel
github_alt: R-devel GitHub organization
navigation:
  - title: Home
    url: /
  - title: Slack Group
    url: slack
  - title: Events
    url: events
  - title: Tutorials & demos
    url: tutorials
  - title: R Development Guide
    url: https://contributor.r-project.org/rdevguide/
  - title: Translations Community Page
    url: https://contributor.r-project.org/translations/
  - title: R Contribution Working Group
    url: working-group
  - title: R Core Developer Page
    url: https://developer.r-project.org/
  - title: R Project Blog
    url: https://blog.r-project.org/
  - title: R SVN CI Dashboard
    url: https://contributor.r-project.org/svn-dashboard
  - title: R Universe
    url: https://r-universe.dev